from typing import Protocol

from app.domain.entities import AccessRequest, ProvisioningJob, Resource, User


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class UserRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> User | None: ...


class ResourceRepository(Protocol):
    async def get(self, resource_id: int) -> Resource | None: ...

    async def list_all(self) -> list[Resource]: ...


class AccessRequestRepository(Protocol):
    async def add(self, request: AccessRequest) -> AccessRequest: ...

    async def get_visible(self, request_id: int, actor: User) -> AccessRequest | None: ...

    async def list_visible(
        self, actor: User, status: str | None = None, resource_id: int | None = None
    ) -> list[AccessRequest]: ...

    async def get_for_update(self, request_id: int) -> AccessRequest | None: ...

    async def save(self, request: AccessRequest) -> None: ...


class ProvisioningJobRepository(Protocol):
    async def add(self, job: ProvisioningJob) -> None: ...

    async def get_by_request(self, request_id: int) -> ProvisioningJob | None: ...

    async def claim_next(self, lease_seconds: int) -> ProvisioningJob | None: ...

    async def save(self, job: ProvisioningJob) -> None: ...


class ProvisioningProvider(Protocol):
    async def provision_access(self, user_id: int, resource_id: int) -> None: ...
